[workspace]
resolver = "2"
members = [
    "crates/streeem-domain",
    "crates/streeem-application",
    "crates/streeem-infrastructure",
    "crates/streeem-presentation",
    "crates/streeem-bin",
]

[workspace.package]
edition = "2024"
version = "0.2.7"
license = "MIT OR Apache-2.0"
publish = false
repository = "https://github.com/3moeslam/streeem"
homepage = "https://github.com/3moeslam/streeem"
description = "Rust TUI that hosts multiple interactive terminals in a staggered grid"
authors = ["Eslam <eslam.abdelkader01@gmail.com>"]

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

